name: task_master_pro
description: A professional project management application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.0
  shared_preferences: ^2.2.0
  flutter_slidable: ^3.0.1
  table_calendar: ^3.0.9
  fl_chart: ^0.65.0
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  flutter_local_notifications: ^16.2.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  dio: ^5.7.0
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - ../static/task_list.csv